export const CATEGORIAS_SERVICIOS = [
  'Electricista',
  'Plomería',
  'Carpinteria',
  'Pintura',
  'Albañilería',
  'Jardinería',
  'Refrigeración',
  'limpieza Profunda',
  'Herrería',
  'Gasfitería',
  'Cerrajería',
  'Tecnologia/Redes',
  'Tapicería',
  'Electrónica',
  'Decoración de Interiores',
  'Fontanería',
  'Arquitectura',
  'Impermeabilización',
  'Diseño de Jardines',
  'Vidriería',
  'Otros'
];